package personal.bs.domain.dto;

import com.alibaba.fastjson.JSONObject;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.solr.client.solrj.beans.Field;
import personal.bs.domain.po.SkuPO;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sku
 *
 * @mbg.generated do_not_delete_during_merge
 */

@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SkuPODto implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.spu_id
     *
     * @mbg.generated
     */
    @Field("sku_id")
    private Integer spuId;

    /**
     * Database Column Remarks:
     *   图片链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.img_url
     *
     * @mbg.generated
     */
    @Field("sku_image")
    private String imgUrl;

    /**
     * Database Column Remarks:
     *   价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.price
     *
     * @mbg.generated
     */
    @Field("sku_price")
    private Double price;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.stock_count
     *
     * @mbg.generated
     */
    @JsonProperty("num")
    private Integer stockCount;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.type
     *
     * @mbg.generated
     */
    @Field("sku_category")
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.is_default
     *
     * @mbg.generated
     */
    @JsonProperty("status")
    private String isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.spec
     *
     * @mbg.generated
     */
    private JSONObject spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.store
     *
     * @mbg.generated
     */
    @Field("sku_seller")
    private String store;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.type_id
     *
     * @mbg.generated
     */
    @Field("sku_category")
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.title
     *
     * @mbg.generated
     */
    @Field("sku_title")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

}