package personal.bs.domain.po;

import com.alibaba.druid.filter.AutoLoad;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.solr.client.solrj.beans.Field;
import org.springframework.data.solr.core.mapping.Dynamic;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Map;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sku
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SkuPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.spu_id
     *
     * @mbg.generated
     */
    @Field("spu_id")
    private Integer spuId;

    /**
     * Database Column Remarks:
     *   图片链接
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.img_url
     *
     * @mbg.generated
     */
    @Field("sku_image")
    private String imgUrl;

    /**
     * Database Column Remarks:
     *   价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.price
     *
     * @mbg.generated
     */
    @Field("sku_price")
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.stock_count
     *
     * @mbg.generated
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.type
     *
     * @mbg.generated
     */
    @Field("sku_category")
    private String type;

    @Dynamic
    @Field("sku_spec_*")
    private Map<String,String> specMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.is_default
     *
     * @mbg.generated
     */
    private String isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.spec
     *
     * @mbg.generated
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.store
     *
     * @mbg.generated
     */
    @Field("sku_seller")
    private String store;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.type_id
     *
     * @mbg.generated
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.title
     *
     * @mbg.generated
     */
    @Field("sku_title")
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.sale_num
     *
     * @mbg.generated
     */
    @Field("sku_salenum")
    private Integer saleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.uploadDate
     *
     * @mbg.generated
     */
    @Field("sku_updatetime")
    private Date uploaddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku.comment
     *
     * @mbg.generated
     */
    @Field("sku_comment")
    private Integer comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}