package personal.bs.domain.po;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table spu
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SpuPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.type1_id
     *
     * @mbg.generated
     */
    private Integer type1Id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.store_id
     *
     * @mbg.generated
     */
    private Integer storeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.sale_num
     *
     * @mbg.generated
     */
    private Integer saleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.upload_date
     *
     * @mbg.generated
     */
    private Date uploadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.type2_id
     *
     * @mbg.generated
     */
    private Integer type2Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.spec_template_id
     *
     * @mbg.generated
     */
    private Integer specTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.caption
     *
     * @mbg.generated
     */
    private String caption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.default_sku_id
     *
     * @mbg.generated
     */
    private Integer defaultSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.is_enable_spec
     *
     * @mbg.generated
     */
    private String isEnableSpec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spu.is_delete
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.id
     *
     * @return the value of spu.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.id
     *
     * @param id the value for spu.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.name
     *
     * @return the value of spu.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.name
     *
     * @param name the value for spu.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.type1_id
     *
     * @return the value of spu.type1_id
     *
     * @mbg.generated
     */
    public Integer getType1Id() {
        return type1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.type1_id
     *
     * @param type1Id the value for spu.type1_id
     *
     * @mbg.generated
     */
    public void setType1Id(Integer type1Id) {
        this.type1Id = type1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.description
     *
     * @return the value of spu.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.description
     *
     * @param description the value for spu.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.store_id
     *
     * @return the value of spu.store_id
     *
     * @mbg.generated
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.store_id
     *
     * @param storeId the value for spu.store_id
     *
     * @mbg.generated
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.sale_num
     *
     * @return the value of spu.sale_num
     *
     * @mbg.generated
     */
    public Integer getSaleNum() {
        return saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.sale_num
     *
     * @param saleNum the value for spu.sale_num
     *
     * @mbg.generated
     */
    public void setSaleNum(Integer saleNum) {
        this.saleNum = saleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.upload_date
     *
     * @return the value of spu.upload_date
     *
     * @mbg.generated
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.upload_date
     *
     * @param uploadDate the value for spu.upload_date
     *
     * @mbg.generated
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.status
     *
     * @return the value of spu.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.status
     *
     * @param status the value for spu.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.type2_id
     *
     * @return the value of spu.type2_id
     *
     * @mbg.generated
     */
    public Integer getType2Id() {
        return type2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.type2_id
     *
     * @param type2Id the value for spu.type2_id
     *
     * @mbg.generated
     */
    public void setType2Id(Integer type2Id) {
        this.type2Id = type2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.pic
     *
     * @return the value of spu.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.pic
     *
     * @param pic the value for spu.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.spec_template_id
     *
     * @return the value of spu.spec_template_id
     *
     * @mbg.generated
     */
    public Integer getSpecTemplateId() {
        return specTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.spec_template_id
     *
     * @param specTemplateId the value for spu.spec_template_id
     *
     * @mbg.generated
     */
    public void setSpecTemplateId(Integer specTemplateId) {
        this.specTemplateId = specTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.caption
     *
     * @return the value of spu.caption
     *
     * @mbg.generated
     */
    public String getCaption() {
        return caption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.caption
     *
     * @param caption the value for spu.caption
     *
     * @mbg.generated
     */
    public void setCaption(String caption) {
        this.caption = caption == null ? null : caption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.default_sku_id
     *
     * @return the value of spu.default_sku_id
     *
     * @mbg.generated
     */
    public Integer getDefaultSkuId() {
        return defaultSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.default_sku_id
     *
     * @param defaultSkuId the value for spu.default_sku_id
     *
     * @mbg.generated
     */
    public void setDefaultSkuId(Integer defaultSkuId) {
        this.defaultSkuId = defaultSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.price
     *
     * @return the value of spu.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.price
     *
     * @param price the value for spu.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.is_enable_spec
     *
     * @return the value of spu.is_enable_spec
     *
     * @mbg.generated
     */
    public String getIsEnableSpec() {
        return isEnableSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.is_enable_spec
     *
     * @param isEnableSpec the value for spu.is_enable_spec
     *
     * @mbg.generated
     */
    public void setIsEnableSpec(String isEnableSpec) {
        this.isEnableSpec = isEnableSpec == null ? null : isEnableSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spu.is_delete
     *
     * @return the value of spu.is_delete
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spu.is_delete
     *
     * @param isDelete the value for spu.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SpuPO other = (SpuPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getType1Id() == null ? other.getType1Id() == null : this.getType1Id().equals(other.getType1Id()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStoreId() == null ? other.getStoreId() == null : this.getStoreId().equals(other.getStoreId()))
            && (this.getSaleNum() == null ? other.getSaleNum() == null : this.getSaleNum().equals(other.getSaleNum()))
            && (this.getUploadDate() == null ? other.getUploadDate() == null : this.getUploadDate().equals(other.getUploadDate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getType2Id() == null ? other.getType2Id() == null : this.getType2Id().equals(other.getType2Id()))
            && (this.getPic() == null ? other.getPic() == null : this.getPic().equals(other.getPic()))
            && (this.getSpecTemplateId() == null ? other.getSpecTemplateId() == null : this.getSpecTemplateId().equals(other.getSpecTemplateId()))
            && (this.getCaption() == null ? other.getCaption() == null : this.getCaption().equals(other.getCaption()))
            && (this.getDefaultSkuId() == null ? other.getDefaultSkuId() == null : this.getDefaultSkuId().equals(other.getDefaultSkuId()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getIsEnableSpec() == null ? other.getIsEnableSpec() == null : this.getIsEnableSpec().equals(other.getIsEnableSpec()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType1Id() == null) ? 0 : getType1Id().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStoreId() == null) ? 0 : getStoreId().hashCode());
        result = prime * result + ((getSaleNum() == null) ? 0 : getSaleNum().hashCode());
        result = prime * result + ((getUploadDate() == null) ? 0 : getUploadDate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getType2Id() == null) ? 0 : getType2Id().hashCode());
        result = prime * result + ((getPic() == null) ? 0 : getPic().hashCode());
        result = prime * result + ((getSpecTemplateId() == null) ? 0 : getSpecTemplateId().hashCode());
        result = prime * result + ((getCaption() == null) ? 0 : getCaption().hashCode());
        result = prime * result + ((getDefaultSkuId() == null) ? 0 : getDefaultSkuId().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getIsEnableSpec() == null) ? 0 : getIsEnableSpec().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", type1Id=").append(type1Id);
        sb.append(", description=").append(description);
        sb.append(", storeId=").append(storeId);
        sb.append(", saleNum=").append(saleNum);
        sb.append(", uploadDate=").append(uploadDate);
        sb.append(", status=").append(status);
        sb.append(", type2Id=").append(type2Id);
        sb.append(", pic=").append(pic);
        sb.append(", specTemplateId=").append(specTemplateId);
        sb.append(", caption=").append(caption);
        sb.append(", defaultSkuId=").append(defaultSkuId);
        sb.append(", price=").append(price);
        sb.append(", isEnableSpec=").append(isEnableSpec);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}