package personal.bs.domain.po;

import java.io.Serializable;
import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table spu_spec
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SpuSpecPO implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spu_id")
    private Integer spuId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spec_id")
    private Integer specId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spec_value_id")
    private Integer specValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spu_id")
    public Integer getSpuId() {
        return spuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spu_id")
    public void setSpuId(Integer spuId) {
        this.spuId = spuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spec_id")
    public Integer getSpecId() {
        return specId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spec_id")
    public void setSpecId(Integer specId) {
        this.specId = specId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spec_value_id")
    public Integer getSpecValueId() {
        return specValueId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: spu_spec.spec_value_id")
    public void setSpecValueId(Integer specValueId) {
        this.specValueId = specValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SpuSpecPO other = (SpuSpecPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getSpuId() == null ? other.getSpuId() == null : this.getSpuId().equals(other.getSpuId()))
            && (this.getSpecId() == null ? other.getSpecId() == null : this.getSpecId().equals(other.getSpecId()))
            && (this.getSpecValueId() == null ? other.getSpecValueId() == null : this.getSpecValueId().equals(other.getSpecValueId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSpuId() == null) ? 0 : getSpuId().hashCode());
        result = prime * result + ((getSpecId() == null) ? 0 : getSpecId().hashCode());
        result = prime * result + ((getSpecValueId() == null) ? 0 : getSpecValueId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", spuId=").append(spuId);
        sb.append(", specId=").append(specId);
        sb.append(", specValueId=").append(specValueId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}