package personal.bs.domain.po;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table store
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class StorePO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   店铺名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   店铺名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   公司电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     * Database Column Remarks:
     *   公司详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.addressDetail
     *
     * @mbg.generated
     */
    private String addressdetail;

    /**
     * Database Column Remarks:
     *   联系人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.linkmanName
     *
     * @mbg.generated
     */
    private String linkmanname;

    /**
     * Database Column Remarks:
     *   联系人手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.linkmanMobile
     *
     * @mbg.generated
     */
    private String linkmanmobile;

    /**
     * Database Column Remarks:
     *   营业执照号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.licenseNumber
     *
     * @mbg.generated
     */
    private String licensenumber;

    /**
     * Database Column Remarks:
     *   法定代表人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.legalPerson
     *
     * @mbg.generated
     */
    private String legalperson;

    /**
     * Database Column Remarks:
     *   审核状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   入驻时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   登录名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.loginname
     *
     * @mbg.generated
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table store
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.id
     *
     * @return the value of store.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.id
     *
     * @param id the value for store.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.name
     *
     * @return the value of store.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.name
     *
     * @param name the value for store.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.nickname
     *
     * @return the value of store.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.nickname
     *
     * @param nickname the value for store.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.password
     *
     * @return the value of store.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.password
     *
     * @param password the value for store.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.telephone
     *
     * @return the value of store.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.telephone
     *
     * @param telephone the value for store.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.addressDetail
     *
     * @return the value of store.addressDetail
     *
     * @mbg.generated
     */
    public String getAddressdetail() {
        return addressdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.addressDetail
     *
     * @param addressdetail the value for store.addressDetail
     *
     * @mbg.generated
     */
    public void setAddressdetail(String addressdetail) {
        this.addressdetail = addressdetail == null ? null : addressdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.linkmanName
     *
     * @return the value of store.linkmanName
     *
     * @mbg.generated
     */
    public String getLinkmanname() {
        return linkmanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.linkmanName
     *
     * @param linkmanname the value for store.linkmanName
     *
     * @mbg.generated
     */
    public void setLinkmanname(String linkmanname) {
        this.linkmanname = linkmanname == null ? null : linkmanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.linkmanMobile
     *
     * @return the value of store.linkmanMobile
     *
     * @mbg.generated
     */
    public String getLinkmanmobile() {
        return linkmanmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.linkmanMobile
     *
     * @param linkmanmobile the value for store.linkmanMobile
     *
     * @mbg.generated
     */
    public void setLinkmanmobile(String linkmanmobile) {
        this.linkmanmobile = linkmanmobile == null ? null : linkmanmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.licenseNumber
     *
     * @return the value of store.licenseNumber
     *
     * @mbg.generated
     */
    public String getLicensenumber() {
        return licensenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.licenseNumber
     *
     * @param licensenumber the value for store.licenseNumber
     *
     * @mbg.generated
     */
    public void setLicensenumber(String licensenumber) {
        this.licensenumber = licensenumber == null ? null : licensenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.legalPerson
     *
     * @return the value of store.legalPerson
     *
     * @mbg.generated
     */
    public String getLegalperson() {
        return legalperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.legalPerson
     *
     * @param legalperson the value for store.legalPerson
     *
     * @mbg.generated
     */
    public void setLegalperson(String legalperson) {
        this.legalperson = legalperson == null ? null : legalperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.status
     *
     * @return the value of store.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.status
     *
     * @param status the value for store.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.create_time
     *
     * @return the value of store.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.create_time
     *
     * @param createTime the value for store.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.loginname
     *
     * @return the value of store.loginname
     *
     * @mbg.generated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.loginname
     *
     * @param loginname the value for store.loginname
     *
     * @mbg.generated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StorePO other = (StorePO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getAddressdetail() == null ? other.getAddressdetail() == null : this.getAddressdetail().equals(other.getAddressdetail()))
            && (this.getLinkmanname() == null ? other.getLinkmanname() == null : this.getLinkmanname().equals(other.getLinkmanname()))
            && (this.getLinkmanmobile() == null ? other.getLinkmanmobile() == null : this.getLinkmanmobile().equals(other.getLinkmanmobile()))
            && (this.getLicensenumber() == null ? other.getLicensenumber() == null : this.getLicensenumber().equals(other.getLicensenumber()))
            && (this.getLegalperson() == null ? other.getLegalperson() == null : this.getLegalperson().equals(other.getLegalperson()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLoginname() == null ? other.getLoginname() == null : this.getLoginname().equals(other.getLoginname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getAddressdetail() == null) ? 0 : getAddressdetail().hashCode());
        result = prime * result + ((getLinkmanname() == null) ? 0 : getLinkmanname().hashCode());
        result = prime * result + ((getLinkmanmobile() == null) ? 0 : getLinkmanmobile().hashCode());
        result = prime * result + ((getLicensenumber() == null) ? 0 : getLicensenumber().hashCode());
        result = prime * result + ((getLegalperson() == null) ? 0 : getLegalperson().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLoginname() == null) ? 0 : getLoginname().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", nickname=").append(nickname);
        sb.append(", password=").append(password);
        sb.append(", telephone=").append(telephone);
        sb.append(", addressdetail=").append(addressdetail);
        sb.append(", linkmanname=").append(linkmanname);
        sb.append(", linkmanmobile=").append(linkmanmobile);
        sb.append(", licensenumber=").append(licensenumber);
        sb.append(", legalperson=").append(legalperson);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", loginname=").append(loginname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}