package personal.bs.controller;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.solr.client.solrj.beans.Field;
import org.springframework.data.solr.core.mapping.Dynamic;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Map;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sku
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SolrSkuPO implements Serializable {

    private Integer id;

    @Field("spu_id")
    private Integer spuId;

    @Field("sku_image")
    private String imgUrl;

    @Field("sku_price")
    private String price;

    @Field("sku_category")
    private String type;

    @Dynamic
    @Field("sku_spec_*")
    private Map<String,String> specMap;

    @Field("sku_seller")
    private String store;

    @Field("sku_title")
    private String title;

    @Field("sku_salenum")
    private Integer saleNum;

    @Field("sku_updatetime")
    private Date uploaddate;

    @Field("sku_comment")
    private Integer comment;
}