package personal.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal.bs.domain.po.OrderPO;
import personal.bs.domain.po.OrderPOExample;

public interface OrderPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    long countByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int deleteByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Delete({
        "delete from order",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Insert({
        "insert into order (address_id, user_id, ",
        "order_status, order_num, ",
        "create_time, pay_time, ",
        "pay_type, trade_num, ",
        "delivery_id, invoice_id, ",
        "pay_status, order_money, ",
        "pay_money)",
        "values (#{addressId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{orderStatus,jdbcType=VARCHAR}, #{orderNum,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{payTime,jdbcType=TIMESTAMP}, ",
        "#{payType,jdbcType=VARCHAR}, #{tradeNum,jdbcType=INTEGER}, ",
        "#{deliveryId,jdbcType=INTEGER}, #{invoiceId,jdbcType=INTEGER}, ",
        "#{payStatus,jdbcType=VARCHAR}, #{orderMoney,jdbcType=VARCHAR}, ",
        "#{payMoney,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int insertSelective(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    List<OrderPO> selectByExample(OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, address_id, user_id, order_status, order_num, create_time, pay_time, pay_type, ",
        "trade_num, delivery_id, invoice_id, pay_status, order_money, pay_money",
        "from order",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal.bs.dao.mapper.OrderPOMapper.BaseResultMap")
    OrderPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderPO record, @Param("example") OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderPO record, @Param("example") OrderPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Update({
        "update order",
        "set address_id = #{addressId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "order_status = #{orderStatus,jdbcType=VARCHAR},",
          "order_num = #{orderNum,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "pay_time = #{payTime,jdbcType=TIMESTAMP},",
          "pay_type = #{payType,jdbcType=VARCHAR},",
          "trade_num = #{tradeNum,jdbcType=INTEGER},",
          "delivery_id = #{deliveryId,jdbcType=INTEGER},",
          "invoice_id = #{invoiceId,jdbcType=INTEGER},",
          "pay_status = #{payStatus,jdbcType=VARCHAR},",
          "order_money = #{orderMoney,jdbcType=VARCHAR},",
          "pay_money = #{payMoney,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrderPO record);
}