package personal.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal.bs.domain.po.OrderItemPO;
import personal.bs.domain.po.OrderItemPOExample;

public interface OrderItemPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    long countByExample(OrderItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    int deleteByExample(OrderItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    @Delete({
        "delete from order_item",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    @Insert({
        "insert into order_item (order_id, sku_id, ",
        "num, store_id, title, ",
        "price, sum)",
        "values (#{orderId,jdbcType=VARCHAR}, #{skuId,jdbcType=INTEGER}, ",
        "#{num,jdbcType=INTEGER}, #{storeId,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DOUBLE}, #{sum,jdbcType=DOUBLE})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(OrderItemPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    int insertSelective(OrderItemPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    List<OrderItemPO> selectByExample(OrderItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, order_id, sku_id, num, store_id, title, price, sum",
        "from order_item",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal.bs.dao.mapper.OrderItemPOMapper.BaseResultMap")
    OrderItemPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderItemPO record, @Param("example") OrderItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderItemPO record, @Param("example") OrderItemPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderItemPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    @Update({
        "update order_item",
        "set order_id = #{orderId,jdbcType=VARCHAR},",
          "sku_id = #{skuId,jdbcType=INTEGER},",
          "num = #{num,jdbcType=INTEGER},",
          "store_id = #{storeId,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DOUBLE},",
          "sum = #{sum,jdbcType=DOUBLE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrderItemPO record);
}