package personal.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal.bs.domain.po.SkuPO;
import personal.bs.domain.po.SkuPOExample;

public interface SkuPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    long countByExample(SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int deleteByExample(SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sku (spu_id, img_url, ",
        "price, stock_count, ",
        "spu_spec_ids)",
        "values (#{spuId,jdbcType=INTEGER}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{stockCount,jdbcType=INTEGER}, ",
        "#{spuSpecIds,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SkuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int insertSelective(SkuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    List<SkuPO> selectByExample(SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, spu_id, img_url, price, stock_count, spu_spec_ids",
        "from sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal.bs.dao.mapper.SkuPOMapper.BaseResultMap")
    SkuPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SkuPO record, @Param("example") SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SkuPO record, @Param("example") SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SkuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Update({
        "update sku",
        "set spu_id = #{spuId,jdbcType=INTEGER},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "stock_count = #{stockCount,jdbcType=INTEGER},",
          "spu_spec_ids = #{spuSpecIds,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SkuPO record);
}