package personal.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal.bs.domain.po.SkuPO;
import personal.bs.domain.po.SkuPOExample;

public interface SkuPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    long countByExample(SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int deleteByExample(SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sku (spu_id, img_url, ",
        "price, stock_count, ",
        "type, is_default, ",
        "spec, store, type_id, ",
        "store_id, title, ",
        "sale_num, uploadDate, ",
        "comment)",
        "values (#{spuId,jdbcType=INTEGER}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{stockCount,jdbcType=INTEGER}, ",
        "#{type,jdbcType=VARCHAR}, #{isDefault,jdbcType=VARCHAR}, ",
        "#{spec,jdbcType=VARCHAR}, #{store,jdbcType=VARCHAR}, #{typeId,jdbcType=INTEGER}, ",
        "#{storeId,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{saleNum,jdbcType=INTEGER}, #{uploaddate,jdbcType=TIMESTAMP}, ",
        "#{comment,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SkuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int insertSelective(SkuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    List<SkuPO> selectByExample(SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, spu_id, img_url, price, stock_count, type, is_default, spec, store, type_id, ",
        "store_id, title, sale_num, uploadDate, comment",
        "from sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal.bs.dao.mapper.SkuPOMapper.BaseResultMap")
    SkuPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SkuPO record, @Param("example") SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SkuPO record, @Param("example") SkuPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SkuPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Update({
        "update sku",
        "set spu_id = #{spuId,jdbcType=INTEGER},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "stock_count = #{stockCount,jdbcType=INTEGER},",
          "type = #{type,jdbcType=VARCHAR},",
          "is_default = #{isDefault,jdbcType=VARCHAR},",
          "spec = #{spec,jdbcType=VARCHAR},",
          "store = #{store,jdbcType=VARCHAR},",
          "type_id = #{typeId,jdbcType=INTEGER},",
          "store_id = #{storeId,jdbcType=INTEGER},",
          "title = #{title,jdbcType=VARCHAR},",
          "sale_num = #{saleNum,jdbcType=INTEGER},",
          "uploadDate = #{uploaddate,jdbcType=TIMESTAMP},",
          "comment = #{comment,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SkuPO record);
}