package personal.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal.bs.domain.po.SpecValuePO;
import personal.bs.domain.po.SpecValuePOExample;

public interface SpecValuePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    long countByExample(SpecValuePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int deleteByExample(SpecValuePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spec_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spec_value (spec_id, value, ",
        "orders)",
        "values (#{specId,jdbcType=INTEGER}, #{value,jdbcType=VARCHAR}, ",
        "#{orders,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SpecValuePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int insertSelective(SpecValuePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    List<SpecValuePO> selectByExample(SpecValuePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, spec_id, value, orders",
        "from spec_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal.bs.dao.mapper.SpecValuePOMapper.BaseResultMap")
    SpecValuePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpecValuePO record, @Param("example") SpecValuePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpecValuePO record, @Param("example") SpecValuePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpecValuePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    @Update({
        "update spec_value",
        "set spec_id = #{specId,jdbcType=INTEGER},",
          "value = #{value,jdbcType=VARCHAR},",
          "orders = #{orders,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpecValuePO record);
}