package personal.bs.dao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal.bs.domain.po.SpecTemplatePO;
import personal.bs.domain.po.SpecTemplatePOExample;

public interface SpecTemplatePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    long countByExample(SpecTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    int deleteByExample(SpecTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spec_template",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spec_template (spec_value_ids, name, ",
        "extend_attributes)",
        "values (#{specValueIds,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{extendAttributes,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SpecTemplatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    int insertSelective(SpecTemplatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    List<SpecTemplatePO> selectByExample(SpecTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, spec_value_ids, name, extend_attributes",
        "from spec_template",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal.bs.dao.mapper.SpecTemplatePOMapper.BaseResultMap")
    SpecTemplatePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpecTemplatePO record, @Param("example") SpecTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpecTemplatePO record, @Param("example") SpecTemplatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpecTemplatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_template
     *
     * @mbg.generated
     */
    @Update({
        "update spec_template",
        "set spec_value_ids = #{specValueIds,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "extend_attributes = #{extendAttributes,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpecTemplatePO record);

    List<Map> selectOptionList();
}