package personal.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal.bs.domain.po.TbGoodsDesc;
import personal.bs.domain.po.TbGoodsDescExample;

public interface TbGoodsDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    long countByExample(TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    int deleteByExample(TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spu_desc",
        "where spu_id = #{spuId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer spuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spu_desc (spu_id, introduction, ",
        "specification_items, custom_attribute_items, ",
        "item_images, package_list, ",
        "sale_service)",
        "values (#{spuId,jdbcType=INTEGER}, #{introduction,jdbcType=VARCHAR}, ",
        "#{specificationItems,jdbcType=VARCHAR}, #{customAttributeItems,jdbcType=VARCHAR}, ",
        "#{itemImages,jdbcType=VARCHAR}, #{packageList,jdbcType=VARCHAR}, ",
        "#{saleService,jdbcType=VARCHAR})"
    })
    int insert(TbGoodsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    int insertSelective(TbGoodsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    List<TbGoodsDesc> selectByExample(TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "spu_id, introduction, specification_items, custom_attribute_items, item_images, ",
        "package_list, sale_service",
        "from spu_desc",
        "where spu_id = #{spuId,jdbcType=INTEGER}"
    })
    @ResultMap("personal.bs.dao.mapper.TbGoodsDescMapper.BaseResultMap")
    TbGoodsDesc selectByPrimaryKey(Integer spuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbGoodsDesc record, @Param("example") TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbGoodsDesc record, @Param("example") TbGoodsDescExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbGoodsDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_desc
     *
     * @mbg.generated
     */
    @Update({
        "update spu_desc",
        "set introduction = #{introduction,jdbcType=VARCHAR},",
          "specification_items = #{specificationItems,jdbcType=VARCHAR},",
          "custom_attribute_items = #{customAttributeItems,jdbcType=VARCHAR},",
          "item_images = #{itemImages,jdbcType=VARCHAR},",
          "package_list = #{packageList,jdbcType=VARCHAR},",
          "sale_service = #{saleService,jdbcType=VARCHAR}",
        "where spu_id = #{spuId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TbGoodsDesc record);
}