package personal1.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal1.bs.domain.po.SkuDO;
import personal1.bs.domain.po.SkuDOExample;

public interface SkuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    long countByExample(SkuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int deleteByExample(SkuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Delete({
        "delete from sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Insert({
        "insert into sku (spu_id, img_url, ",
        "price, repertory, ",
        "spu_spec_ids)",
        "values (#{spuId,jdbcType=INTEGER}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{repertory,jdbcType=VARCHAR}, ",
        "#{spuSpecIds,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SkuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int insertSelective(SkuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    List<SkuDO> selectByExample(SkuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, spu_id, img_url, price, repertory, spu_spec_ids",
        "from sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal1.bs.dao.mapper.SkuDOMapper.BaseResultMap")
    SkuDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SkuDO record, @Param("example") SkuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SkuDO record, @Param("example") SkuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SkuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku
     *
     * @mbg.generated
     */
    @Update({
        "update sku",
        "set spu_id = #{spuId,jdbcType=INTEGER},",
          "img_url = #{imgUrl,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "repertory = #{repertory,jdbcType=VARCHAR},",
          "spu_spec_ids = #{spuSpecIds,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SkuDO record);
}