package personal1.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal1.bs.domain.po.SpecValueDO;
import personal1.bs.domain.po.SpecValueDOExample;

public interface SpecValueDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    long countByExample(SpecValueDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int deleteByExample(SpecValueDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spec_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spec_value (spec_id, value)",
        "values (#{specId,jdbcType=INTEGER}, #{value,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SpecValueDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int insertSelective(SpecValueDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    List<SpecValueDO> selectByExample(SpecValueDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, spec_id, value",
        "from spec_value",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal1.bs.dao.mapper.SpecValueDOMapper.BaseResultMap")
    SpecValueDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpecValueDO record, @Param("example") SpecValueDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpecValueDO record, @Param("example") SpecValueDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpecValueDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec_value
     *
     * @mbg.generated
     */
    @Update({
        "update spec_value",
        "set spec_id = #{specId,jdbcType=INTEGER},",
          "value = #{value,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpecValueDO record);
}