package personal1.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal1.bs.domain.po.SpecDO;
import personal1.bs.domain.po.SpecDOExample;

public interface SpecDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    long countByExample(SpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int deleteByExample(SpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spec (name, type_id)",
        "values (#{name,jdbcType=VARCHAR}, #{typeId,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int insertSelective(SpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    List<SpecDO> selectByExample(SpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, type_id",
        "from spec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal1.bs.dao.mapper.SpecDOMapper.BaseResultMap")
    SpecDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpecDO record, @Param("example") SpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpecDO record, @Param("example") SpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spec
     *
     * @mbg.generated
     */
    @Update({
        "update spec",
        "set name = #{name,jdbcType=VARCHAR},",
          "type_id = #{typeId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpecDO record);
}