package personal1.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal1.bs.domain.po.SpuDO;
import personal1.bs.domain.po.SpuDOExample;

public interface SpuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    long countByExample(SpuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    int deleteByExample(SpuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spu (name, type_id, ",
        "description, store_id, ",
        "sale_num, upload_date, ",
        "status)",
        "values (#{name,jdbcType=VARCHAR}, #{typeId,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{storeId,jdbcType=INTEGER}, ",
        "#{saleNum,jdbcType=INTEGER}, #{uploadDate,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SpuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    int insertSelective(SpuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    List<SpuDO> selectByExample(SpuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, type_id, description, store_id, sale_num, upload_date, status",
        "from spu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal1.bs.dao.mapper.SpuDOMapper.BaseResultMap")
    SpuDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpuDO record, @Param("example") SpuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpuDO record, @Param("example") SpuDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu
     *
     * @mbg.generated
     */
    @Update({
        "update spu",
        "set name = #{name,jdbcType=VARCHAR},",
          "type_id = #{typeId,jdbcType=INTEGER},",
          "description = #{description,jdbcType=VARCHAR},",
          "store_id = #{storeId,jdbcType=INTEGER},",
          "sale_num = #{saleNum,jdbcType=INTEGER},",
          "upload_date = #{uploadDate,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpuDO record);
}