package personal1.bs.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import personal1.bs.domain.po.SpuSpecDO;
import personal1.bs.domain.po.SpuSpecDOExample;

public interface SpuSpecDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    long countByExample(SpuSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int deleteByExample(SpuSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    @Delete({
        "delete from spu_spec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    @Insert({
        "insert into spu_spec (spu_id, spec_id, ",
        "spec_value_id)",
        "values (#{spuId,jdbcType=INTEGER}, #{specId,jdbcType=INTEGER}, ",
        "#{specValueId,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(SpuSpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int insertSelective(SpuSpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    List<SpuSpecDO> selectByExample(SpuSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, spu_id, spec_id, spec_value_id",
        "from spu_spec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("personal1.bs.dao.mapper.SpuSpecDOMapper.BaseResultMap")
    SpuSpecDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpuSpecDO record, @Param("example") SpuSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpuSpecDO record, @Param("example") SpuSpecDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpuSpecDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spu_spec
     *
     * @mbg.generated
     */
    @Update({
        "update spu_spec",
        "set spu_id = #{spuId,jdbcType=INTEGER},",
          "spec_id = #{specId,jdbcType=INTEGER},",
          "spec_value_id = #{specValueId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SpuSpecDO record);
}